setupvars:
  environmentTag: PROD
  owner: Core Engineering Team
  technicalTeam: Core Engineering Team
  businessTeam: Client Service Analysts
  tier: APP
  isngp: yes
  ageroService: NGP
  complianceType: NA
  application: connectedvehicle

  classificationLabel: Level2/Confidential
  accountId: 550632061203
  vpc:
    securityGroupIds:
      - sg-0b669e24a9df99989
    subnetIds:
      - subnet-0a66002494e2bbf45
      - subnet-08a68780ef8b6a06c
      - subnet-0dedeaa528b807223
  usageRateLimit: 1000
  usageBurstLimit: 500
  destinationArn: arn:aws:logs:us-east-1:729328028396:destination:aws-fh-destination-cloudwatchevents

  kmsKey: arn:aws:kms:us-east-1:550632061203:key/b751679a-3883-4c08-a6d8-095762305da0   #prod

  customDomain:
    Fn::ImportValue: connectedvehicle-prod-domain-name

  notifications:
    - protocol: email
      endpoint: hkaur@agero.com
    - protocol: email
      endpoint: cogl1-app@agero.com

  dashboard: true
