name: 1.0.$(Rev:r) #build number. Can be referenced using the $(build.buildnumber) system variable. $(Rev:r) is auto-incrementing.
# YAML file in the main branch
schedules:

- cron: "0 */1 * * *"
  displayName: Daily Every 1 hr build
  branches:
    include:
    - main
    
stages:
  - stage: Deploy_US_East_1_QA
    pool: core_platform_nonprod
    jobs:
      - job: CoreTeamPostmanTests
        displayName: Execute Automation tests - QA
        steps:
            - script: |
                make automation-test stage=qa
              displayName: Automation API Tests-QA

            - script: |
                make apigee-automation-test stage=qa
              displayName: Automation APIGEE Tests-QA      

            - task: PublishTestResults@2
              condition: succeededOrFailed()
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: '**/apiTestResults.xml'
                testRunTitle: 'Publish test results for automation QA'

  - stage: Deploy_US_East_1_Stage
    pool: core_platform_nonprod
    jobs:
      - job: CoreTeamPostmanTests
        displayName: Execute Postman API tests in Stage
        pool: core_platform_nonprod
        steps:
            - script: |
                make automation-test stage=stage
              displayName: Automation API Tests-Stage

            - script: |
                make apigee-automation-test stage=stage
              displayName: Apigee API Tests-Stage                         

            - task: PublishTestResults@2
              condition: succeededOrFailed()
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: '**/apiTestResults.xml'
                testRunTitle: 'Publish test results for automation Stage'

  