setupvars:
  accountId: 282323038758
  certArn: arn:aws:acm:us-east-1:282323038758:certificate/499fa8d3-c690-462b-b1ae-c150da82e184
  hostedZoneId: ZVCO53IYIZ0FV
  environmentTag: STAGE
  vpc:
    securityGroupIds:
      - sg-0f35e3bce51c8c4d6
    subnetIds:
      - subnet-0e108d130bf063786
      - subnet-061ec64b6ca16e19c
  owner: Core Engineering Team
  technicalTeam: Core Engineering Team
  businessTeam: Client Service Analysts
  ageroService: NGP
  complianceType: NA
  tier: APP
  isngp: yes
  application: connectedvehicle
