setupvars:
  environmentTag: QA
  owner: Core Engineering Team
  technicalTeam: Core Engineering Team
  businessTeam: Client Service Analysts
  ageroService: NGP
  tier: APP
  isngp: yes
  complianceType: NA
  application: connectedvehicle

  classificationLabel: Level2/Confidential
  accountId: 282323038758
  vpc:
    securityGroupIds:
      - sg-0f35e3bce51c8c4d6
    subnetIds:
      - subnet-0e108d130bf063786
      - subnet-061ec64b6ca16e19c
  usageRateLimit: 1000
  usageBurstLimit: 500
  kmsKey: arn:aws:kms:us-east-1:282323038758:key/22e09c40-8865-4b7e-b59c-27dc5fb9c60e  #DEVQA
  destinationArn: arn:aws:logs:us-east-1:729328028396:destination:aws-fh-destination-cloudwatchevents

  customDomain:
    Fn::ImportValue: connectedvehicle-nonprod-domain-name
  notifications:
    - protocol: email
      endpoint: hkaur@agero.com
    - protocol: email
      endpoint: CogL1-App@agero.com

  dashboard: false
