setupvars:
  environmentTag: PROD
  owner: Core Engineering Team
  technicalTeam: Core Engineering Team
  businessTeam: Client Service Analysts
  ageroService: NGP
  complianceType: NA
  tier: APP
  isngp: yes
  application: connectedvehicle

  classificationLabel: Level2/Confidential
  accountId: 550632061203
  vpc:
    securityGroupIds:
      - sg-0f9c7909a8a33cc88
    subnetIds:
      - subnet-071abbd930edfaf73
      - subnet-0a02d6ecf76f388d8
      - subnet-0356e8b6190207a0d
  usageRateLimit: 1000
  usageBurstLimit: 500
  kmsKey: arn:aws:kms:us-east-1:550632061203:key/b751679a-3883-4c08-a6d8-095762305da0   #prod
  destinationArn: arn:aws:logs:us-west-2:729328028396:destination:aws-fh-destination-cloudwatchevents-us-west-2

  customDomain:
    Fn::ImportValue: connectedvehicle-prod-domain-name

  notifications:
    - protocol: email
      endpoint: hkaur@agero.com
    - protocol: email
      endpoint: CogL1-App@agero.com

  dashboard: true
