setupvar:
    environmentTag: PROD
    owner: Core Engineering Team
    technicalTeam: Core Engineering Team
    businessTeam: Client Service Analysts
    ageroService: NGP
    complianceType: NA
    tier: DATA
    isngp: yes
    application: connectedvehicle

    classificationLabel: Level2/Confidential
    accountId: 550632061203
