<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="RequestVehicleLocation" targetNamespace="http://xmlns.hughestelematics.com/RequestVehicleLocation/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://xmlns.hughestelematics.com/VehicleLocation" xmlns:WL5G3N2="http://xmlns.hughestelematics.com/RequestVehicleLocation/" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://xmlns.hughestelematics.com/RequestVehicleLocation/" xmlns:vl="http://xmlns.hughestelematics.com/VehicleLocation" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://xmlns.hughestelematics.com/VehicleLocation" schemaLocation="RequestVehicleLocation.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="LocateVehicleRequest">
    <WL5G3N0:part element="WL5G3N1:VehicleLocationRequest" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="LocateVehicleResponse">
    <WL5G3N0:part element="WL5G3N1:VehicleLocationResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="RequestVehicleLocationPortType">
    <WL5G3N0:operation name="RequestVehicleLocation">
      <WL5G3N0:input message="WL5G3N2:LocateVehicleRequest"/>
      <WL5G3N0:output message="WL5G3N2:LocateVehicleResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="RequestVehicleLocation" type="WL5G3N2:RequestVehicleLocationPortType">
    <WL5G3N3:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="RequestVehicleLocation">
      <WL5G3N3:operation soapAction="http://xmlns.hughestelematics.com/RequestVehicleLocationPortType/RequestVehicleLocation"/>
      <WL5G3N0:input>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="RequestVehicleLocation">
    <WL5G3N0:port binding="WL5G3N2:RequestVehicleLocation" name="RequestVehicleLocation">
      <WL5G3N3:address location="https://gwoutstage.ageroappsnonprod.corppvt.cloud/VW/api-sit.vtitel.com/SOAP/RequestVehicleLocation"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
  <WL5G3N0:documentation>Copyright (c) 2016 Verizon. All Rights Reserved.</WL5G3N0:documentation>
</WL5G3N0:definitions>